### ISSUE TITLE
Rendered snippets don't build correct links to other symbols

### ISSUE THREAD

**Issue by Joannis** [tayloraswift/swift-unidoc#262]
Links are rendered as such:

```html
<span class="xv" target="_blank" rel="external" href="https://swiftinit.org/docs/swift-nio/niocore/eventloop.makecompletedfuture(withresultof:)">makeCompletedFuture</span>
```

**Comment by tayloraswift** [comment]
this bug not only affects snippets, it also affects all links written with custom precompiled link text, such as `[click here](doc:_Concurrency/AsyncStream)`. we just didn’t notice until now because normal symbol links (` ``_Concurrency/AsyncStream`` `) inject themselves directly into HTML and were therefore immune to this bug.

this was a renderer-level problem and the fix does not require any docs to be recompiled or relinked.

**Comment by tayloraswift** [comment]
deployed to Swiftinit
