### ISSUE TITLE
Canonical url / noindex issue for docs pages

### ISSUE THREAD

**Issue by tib** [tayloraswift/swift-unidoc#309]
By doing a quick [search](https://www.google.com/search?q=site:swiftinit.org+logging-for-server-side-swift-apps&sca_esv=8555417468704b0c&sca_upv=1&source=hp&ei=pqijZrOgNJzFwPAPte-KiAU&iflsig=AL9hbdgAAAAAZqO2tjSiCRAux5IWpEtqNN92rlf2Imy1&ved=0ahUKEwizi7Dh68SHAxWcIhAIHbW3AlEQ4dUDCBY&uact=5&oq=site:swiftinit.org+logging-for-server-side-swift-apps&gs_lp=Egdnd3Mtd2l6IjVzaXRlOnN3aWZ0aW5pdC5vcmcgbG9nZ2luZy1mb3Itc2VydmVyLXNpZGUtc3dpZnQtYXBwc0i4bFAAWNVkcAJ4AJABAJgBqAGgAecLqgEEMTYuMrgBA8gBAPgBAfgBApgCBaAC1wPCAgsQLhiABBjRAxjHAcICBRAAGIAEwgIFEC4YgATCAg4QLhiABBjHARiOBRivAcICCBAuGIAEGNQCwgIKEAAYgAQYRhj5AcICCxAuGIAEGMcBGK8BwgIHEAAYgAQYCpgDAJIHAzQuMaAH-EE&sclient=gws-wiz), I discovered that the generated docs are getting indexed by search engines. 

The canonical url is self-referencing for these pages, but we're also publishing these articles on swiftonserver.com. 

The canonical url should point to the proper site or a noindex tag should be used for these pages: `<meta name="robots" content="noindex">`. 

Otherwise search indexes will rank these pages down, due to duplicate content issues.

Many thanks if you have time for a quick fix. 🙏

**Comment by tayloraswift** [comment]
i just pushed an update to the site adding `Disallow: /docs/joannis.swiftonserver-site/` to the robots.txt. they should disappear from Google’s index over the next couple weeks.

i believe Google crawled these pages because @Joannis was tagging semver releases as a workaround to Swiftinit’s lack of git branch support at the time, causing its docs to appear under `/docs`, which is indexable by default. it doesn’t look like the docs for `swift-on-server.site` are affected by this issue, as they publish to `/hist` which is globally blocked.
